extends Node

## Emitted when the leader broadcasts a follow/freeze command to the family.
signal command_broadcast(new_state: int)

## Emitted when a command propagates sound, detailing origin, size, and classification.
signal sound_emitted(origin: Vector3, radius: float, is_shout: bool)

## Emitted when a companion or player is captured by the Seeker.
signal game_over

## Emitted when a toddler chirps, detailing origin and sound radius.
signal toddler_chirped(origin: Vector3, radius: float)


## Distance threshold beyond which commands require shouting.
const WHISPER_LIMIT_DISTANCE: float = 6.0

## Sound radius generated by a silent whisper command.
const WHISPER_SOUND_RADIUS: float = 2.0

## Sound radius generated by a loud shout command.
const SHOUT_SOUND_RADIUS: float = 15.0

## Tracks active family members currently spawned in the scene.
var active_members: Array[Node3D] = []

## Reference to the player character in the scene.
var player: Node3D = null

func register_player(p_player: Node3D) -> void:
	player = p_player

func unregister_player() -> void:
	player = null

func register_member(member: Node3D) -> void:
	if not active_members.has(member):
		active_members.append(member)

func unregister_member(member: Node3D) -> void:
	active_members.erase(member)

## Sorts family members dynamically by distance to the player to prevent scrambling.
func update_queue_order() -> void:
	if not player or active_members.is_empty():
		return
	active_members.sort_custom(
		func(a, b):
			var dist_a: float = player.global_position.distance_to(a.global_position)
			var dist_b: float = player.global_position.distance_to(b.global_position)
			return dist_a < dist_b
	)

## Returns the index of a family member within the escort line.
func get_follow_index(member: Node3D) -> int:
	return active_members.find(member)

## Broadcasts follow command (0) and registers sound circle origin.
func broadcast_follow(player_pos: Vector3) -> void:
	update_queue_order()
	var sound_info: Dictionary = _calculate_sound_propagation(player_pos)
	sound_emitted.emit(player_pos, sound_info.radius, sound_info.is_shout)
	command_broadcast.emit(0) # State.FOLLOW

## Broadcasts freeze command (1) and registers sound circle origin.
func broadcast_freeze(player_pos: Vector3) -> void:
	update_queue_order()
	var sound_info: Dictionary = _calculate_sound_propagation(player_pos)
	sound_emitted.emit(player_pos, sound_info.radius, sound_info.is_shout)
	
	# Centralized coordinated cover assignment
	assign_hiding_covers()
	
	command_broadcast.emit(1) # State.FREEZE

## Coordinated matchmaking algorithm to allocate best closest cover zones for everyone
func assign_hiding_covers() -> void:
	# Release existing cover assignments first
	for member in active_members:
		if is_instance_valid(member) and member.has_method("release_cover"):
			member.call("release_cover")
			
	var zones: Array[Node] = Engine.get_main_loop().get_nodes_in_group("cover_zones")
	var members_needing_cover: Array[FamilyMember] = []
	for member: FamilyMember in active_members:
		if is_instance_valid(member) and member.is_inside_tree():
			members_needing_cover.append(member)
			
	# Sort by size restrictiveness (Large first, then Medium, then Small)
	members_needing_cover.sort_custom(
		func(a, b):
			var size_rank: Dictionary = {"Large": 3, "Medium": 2, "Small": 1}
			var a_rank: int = size_rank.get(a.get_size_class(), 0)
			var b_rank: int = size_rank.get(b.get_size_class(), 0)
			return a_rank > b_rank
	)
	
	# Coordinated assignment
	for member: FamilyMember in members_needing_cover:
		var best_zone: CoverZone = null
		var min_dist: float = 99999.0
		var my_size: String = member.get_size_class()
		
		for zone in zones:
			if zone is CoverZone and zone.has_space_for(my_size):
				var dist: float = abs(zone.global_position.x - member.global_position.x)
				if dist < min_dist:
					min_dist = dist
					best_zone = zone
					
		if best_zone:
			member._assigned_cover = best_zone
			member._cover_target_x = best_zone.assign_actor(member)
			member.is_hidden = false
			print("[FamilyManager] Central assignment: %s to %s at X: %0.2f" % [member.name, best_zone.name, member._cover_target_x])

func _calculate_sound_propagation(player_pos: Vector3) -> Dictionary:
	var max_dist: float = 0.0
	
	for member in active_members:
		if is_instance_valid(member):
			var dist: float = player_pos.distance_to(member.global_position)
			if dist > max_dist:
				max_dist = dist
				
	var is_shout: bool = max_dist > WHISPER_LIMIT_DISTANCE
	var radius: float = SHOUT_SOUND_RADIUS if is_shout else WHISPER_SOUND_RADIUS
	
	if is_shout and not active_members.is_empty():
		print("[Whisper Network] SHOUT! Sound radius: %f units (Farthest member is %0.1f units away)" % [radius, max_dist])
	else:
		print("[Whisper Network] Whisper. Sound radius: %f units" % radius)
		
	return {"radius": radius, "is_shout": is_shout}

## Triggers a toddler chirp sound circle event.
func emit_toddler_chirp(origin: Vector3, radius: float) -> void:
	toddler_chirped.emit(origin, radius)
	print("[Whisper Network] Toddler Chirp! Sound emitted at %s. Radius: %0.1f units" % [str(origin), radius])

## Returns the nearest active companion matching the required class to a given position.
func get_nearest_member_of_class(req_class: String, pos: Vector3) -> Node3D:
	var nearest_member: Node3D = null
	var min_dist: float = 99999.0
	
	for member in active_members:
		if not is_instance_valid(member):
			continue
			
		var matches := false
		if req_class == "Any":
			matches = true
		elif req_class == "Adult" and member.has_method("is_adult_class") and member.call("is_adult_class"):
			matches = true
		elif req_class == "Toddler" and member.has_method("is_toddler_class") and member.call("is_toddler_class"):
			matches = true
		elif req_class == "Elder" and member.has_method("is_elder_class") and member.call("is_elder_class"):
			matches = true
			
		if matches:
			var dist: float = pos.distance_to(member.global_position)
			if dist < min_dist:
				min_dist = dist
				nearest_member = member
				
	return nearest_member

## Returns the nearest active Adult companion to a given position (wrapper for backward compatibility).
func get_nearest_adult(pos: Vector3) -> Node3D:
	return get_nearest_member_of_class("Adult", pos)

