extends Node

## Emitted when the leader broadcasts a follow/freeze command to the family.
signal command_broadcast(new_state: int)

## Emitted when a command propagates sound, detailing origin, size, and classification.
signal sound_emitted(origin: Vector3, radius: float, is_shout: bool)

## Emitted when a toddler chirps, detailing origin and sound radius.
signal toddler_chirped(origin: Vector3, radius: float)


## Distance threshold beyond which commands require shouting.
const WHISPER_LIMIT_DISTANCE: float = 6.0

## Sound radius generated by a silent whisper command.
const WHISPER_SOUND_RADIUS: float = 2.0

## Sound radius generated by a loud shout command.
const SHOUT_SOUND_RADIUS: float = 15.0

## Tracks active family members currently spawned in the scene.
var active_members: Array[Node3D] = []

## Reference to the player character in the scene.
var player: Node3D = null

func register_player(p_player: Node3D) -> void:
	player = p_player

func unregister_player() -> void:
	player = null

func register_member(member: Node3D) -> void:
	if not active_members.has(member):
		active_members.append(member)

func unregister_member(member: Node3D) -> void:
	active_members.erase(member)

## Sorts family members dynamically by distance to the player to prevent scrambling.
func update_queue_order() -> void:
	if not player or active_members.is_empty():
		return
	active_members.sort_custom(
		func(a, b):
			var dist_a: float = player.global_position.distance_to(a.global_position)
			var dist_b: float = player.global_position.distance_to(b.global_position)
			return dist_a < dist_b
	)

## Returns the index of a family member within the escort line.
func get_follow_index(member: Node3D) -> int:
	return active_members.find(member)

## Broadcasts follow command (0) and registers sound circle origin.
func broadcast_follow(player_pos: Vector3) -> void:
	update_queue_order()
	var sound_info: Dictionary = _calculate_sound_propagation(player_pos)
	sound_emitted.emit(player_pos, sound_info.radius, sound_info.is_shout)
	command_broadcast.emit(0) # State.FOLLOW

## Broadcasts freeze command (1) and registers sound circle origin.
func broadcast_freeze(player_pos: Vector3) -> void:
	update_queue_order()
	var sound_info: Dictionary = _calculate_sound_propagation(player_pos)
	sound_emitted.emit(player_pos, sound_info.radius, sound_info.is_shout)
	command_broadcast.emit(1) # State.FREEZE

func _calculate_sound_propagation(player_pos: Vector3) -> Dictionary:
	var max_dist: float = 0.0
	
	for member in active_members:
		if is_instance_valid(member):
			var dist: float = player_pos.distance_to(member.global_position)
			if dist > max_dist:
				max_dist = dist
				
	var is_shout: bool = max_dist > WHISPER_LIMIT_DISTANCE
	var radius: float = SHOUT_SOUND_RADIUS if is_shout else WHISPER_SOUND_RADIUS
	
	if is_shout and not active_members.is_empty():
		print("[Whisper Network] SHOUT! Sound radius: %f units (Farthest member is %0.1f units away)" % [radius, max_dist])
	else:
		print("[Whisper Network] Whisper. Sound radius: %f units" % radius)
		
	return {"radius": radius, "is_shout": is_shout}

## Triggers a toddler chirp sound circle event.
func emit_toddler_chirp(origin: Vector3, radius: float) -> void:
	toddler_chirped.emit(origin, radius)
	print("[Whisper Network] Toddler Chirp! Sound emitted at %s. Radius: %0.1f units" % [str(origin), radius])

## Returns the nearest active Adult companion to a given position.
func get_nearest_adult(pos: Vector3) -> Node3D:
	var nearest_adult: Node3D = null
	var min_dist: float = 99999.0
	
	for member in active_members:
		if is_instance_valid(member) and member.has_method("is_adult_class") and member.call("is_adult_class"):
			var dist: float = pos.distance_to(member.global_position)
			if dist < min_dist:
				min_dist = dist
				nearest_adult = member
				
	return nearest_adult

